// Subly — Popular Service Presets (INR / Rupees)
// Pre-configured trial days, Indian Rupee pricing, and cancellation URLs

import { BillingCycle } from '../types';

export interface ServicePreset {
  id: string;
  name: string;
  category: 'Popular' | 'Streaming' | 'Design' | 'Music' | 'AI & Tools' | 'Productivity';
  badge: string; // e.g. "30d free"
  trialDays: number;
  defaultPrice: number;
  currency: string;
  billingCycle: BillingCycle;
  cancellationUrl: string;
  brandColor: string;
  iconLetter: string;
}

export const SERVICE_PRESETS: ServicePreset[] = [
  {
    id: 'spotify',
    name: 'Spotify Premium',
    category: 'Popular',
    badge: '30 days free',
    trialDays: 30,
    defaultPrice: 119,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://www.spotify.com/account/subscription',
    brandColor: '#1DB954',
    iconLetter: 'S',
  },
  {
    id: 'youtube',
    name: 'YouTube Premium',
    category: 'Popular',
    badge: '30 days free',
    trialDays: 30,
    defaultPrice: 149,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://www.youtube.com/paid_memberships',
    brandColor: '#FF0000',
    iconLetter: 'Y',
  },
  {
    id: 'amazon-prime',
    name: 'Amazon Prime',
    category: 'Popular',
    badge: '30 days free',
    trialDays: 30,
    defaultPrice: 299,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://www.amazon.in/mc/manage',
    brandColor: '#00A8E1',
    iconLetter: 'A',
  },
  {
    id: 'canva',
    name: 'Canva Pro',
    category: 'Popular',
    badge: '30 days free',
    trialDays: 30,
    defaultPrice: 499,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://www.canva.com/settings/billing-and-teams',
    brandColor: '#00C4CC',
    iconLetter: 'C',
  },
  {
    id: 'disney-hotstar',
    name: 'JioCinema / Hotstar',
    category: 'Streaming',
    badge: '7 days free',
    trialDays: 7,
    defaultPrice: 299,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://www.hotstar.com/in/mypage',
    brandColor: '#113CCF',
    iconLetter: 'H+',
  },
  {
    id: 'netflix',
    name: 'Netflix',
    category: 'Streaming',
    badge: 'Active Plan',
    trialDays: 30,
    defaultPrice: 199,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://www.netflix.com/youraccount',
    brandColor: '#E50914',
    iconLetter: 'N',
  },
  {
    id: 'apple-music',
    name: 'Apple Music / One',
    category: 'Music',
    badge: '30 days free',
    trialDays: 30,
    defaultPrice: 99,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://support.apple.com/billing',
    brandColor: '#FC3C44',
    iconLetter: '🍎',
  },
  {
    id: 'adobe-cc',
    name: 'Adobe Creative Cloud',
    category: 'Design',
    badge: '7 days free',
    trialDays: 7,
    defaultPrice: 4230,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://account.adobe.com/plans',
    brandColor: '#FF0000',
    iconLetter: 'Ad',
  },
  {
    id: 'chatgpt-plus',
    name: 'ChatGPT Plus',
    category: 'AI & Tools',
    badge: '7 days free',
    trialDays: 7,
    defaultPrice: 1999,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://chat.openai.com/#settings',
    brandColor: '#10A37F',
    iconLetter: 'AI',
  },
  {
    id: 'linkedin-prem',
    name: 'LinkedIn Premium',
    category: 'Productivity',
    badge: '30 days free',
    trialDays: 30,
    defaultPrice: 1599,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://www.linkedin.com/premium/cancel',
    brandColor: '#0A66C2',
    iconLetter: 'in',
  },
  {
    id: 'audible',
    name: 'Audible India',
    category: 'Popular',
    badge: '30 days free',
    trialDays: 30,
    defaultPrice: 199,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://www.audible.in/account/overview',
    brandColor: '#F8991C',
    iconLetter: 'Au',
  },
  {
    id: 'duolingo',
    name: 'Duolingo Super',
    category: 'Productivity',
    badge: '14 days free',
    trialDays: 14,
    defaultPrice: 399,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://www.duolingo.com/settings/super',
    brandColor: '#58CC02',
    iconLetter: '🦉',
  },
  {
    id: 'nordvpn',
    name: 'NordVPN',
    category: 'AI & Tools',
    badge: '30 days risk-free',
    trialDays: 30,
    defaultPrice: 499,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://my.nordaccount.com/billing',
    brandColor: '#4687FF',
    iconLetter: 'N',
  },
  {
    id: 'grammarly',
    name: 'Grammarly Premium',
    category: 'Productivity',
    badge: '7 days free',
    trialDays: 7,
    defaultPrice: 999,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://account.grammarly.com/subscription',
    brandColor: '#15C39A',
    iconLetter: 'G',
  },
  {
    id: 'headspace',
    name: 'Headspace',
    category: 'Productivity',
    badge: '14 days free',
    trialDays: 14,
    defaultPrice: 499,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://www.headspace.com/subscription/manage',
    brandColor: '#F47D31',
    iconLetter: 'H',
  },
  {
    id: 'blinkist',
    name: 'Blinkist Premium',
    category: 'Productivity',
    badge: '7 days free',
    trialDays: 7,
    defaultPrice: 399,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://www.blinkist.com/en/settings/account',
    brandColor: '#2CE080',
    iconLetter: 'B',
  },
  {
    id: 'crunchyroll',
    name: 'Crunchyroll Mega Fan',
    category: 'Streaming',
    badge: '14 days free',
    trialDays: 14,
    defaultPrice: 99,
    currency: 'INR',
    billingCycle: 'monthly',
    cancellationUrl: 'https://www.crunchyroll.com/account/membership',
    brandColor: '#F47521',
    iconLetter: 'CR',
  },
];
